//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescripcionProductos
    {
        public int IdFactura { get; set; }
        public int IdProducto { get; set; }
        public decimal Precio { get; set; }
        public decimal CantidadVendida { get; set; }
        public string NombreProducto { get; set; }
    }
}
